<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-12-03 22:05
 */

namespace backend\models\form;

use yii;
use common\libs\Constants;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class BannerForm extends \Common\models\Options
{
    public $img;

    public $target = Constants::TARGET_BLANK;

    public $link;

    public $sort = 0;

    public $desc;

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => yii::t('app', 'Sign'),
            'tips' => yii::t('app', 'Description'),
            'img' => yii::t('app', 'Image'),
            'target' => yii::t('app', 'Target'),
            'link' => yii::t('app', 'Jump Link'),
            'sort' => yii::t('app', 'Sort'),
            'desc' => yii::t('app', 'Description'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'unique'],
            [['name'],  'match', 'pattern' => '/^[a-zA-Z0-9_]+$/', 'message' => yii::t('app', 'Only includes alphabet,_,and number')],
            [['name', 'tips'], 'required'],
            [['sort'], 'integer'],
            [['target', 'link', 'desc'], 'string'],
            [['img'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, webp'],
        ];
    }

    public function scenarios()
    {
        return [
            'type' => ['name', 'group', 'tips'],
            'banner' => ['img', 'target', 'link', 'sort', 'desc'],
        ];
    }

    public function beforeSave($insert)
    {
        $this->type = self::TYPE_BANNER;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getBannersById($id)
    {
        $model = self::findOne($id);
        $banners = json_decode($model->value);
        if($banners == null) $banners = [];
        $models = [];
        foreach ($banners as $banner){
            $models[] = new self([
                'id' => $model->id,
                'name' => $model->name,
                'img' => $banner->img,
                'target' => $banner->target,
                'desc' => $banner->desc,
                'link' => $banner->link,
                'sort' => $banner->sort,
            ]);
        }
        return $models;
    }

    public function getBannerByImg($id, $img)
    {
        $models = $this->getBannersById($id);
        foreach ($models as $model){
            if( $model->img == $img ) {
                return $model;
            }
        }
        throw new NotFoundHttpException("Cannot find id $id img $img");
    }

    public function saveBanner($id, $img='')
    {
        $model = self::findOne($id);
        $banners = json_decode($model->value, true);
        if( $banners == null ) $banners = [];
        $insert = $img == '' ? true : false;

        $upload = UploadedFile::getInstance($this, 'img');
        if ($upload !== null) {
            $uploadPath = yii::getAlias('@uploads/setting/banner');
            if (! FileHelper::createDirectory($uploadPath)) {
                $this->addError('img', "Create directory failed " . $uploadPath);
                return false;
            }
            $fullName = $uploadPath . uniqid() . '_' . $upload->baseName . '.' . $upload->extension;
            if (! $upload->saveAs($fullName)) {
                $this->addError('img', yii::t('app', 'Upload {attribute} error: ' . $upload->error, ['attribute' => yii::t('app', 'Thumb')]) . ': ' . $fullName);
                return false;
            }
            $this->img = str_replace(yii::getAlias('@frontend/web'), '', $fullName);
            if( !$insert ){
                $file = yii::getAlias('@frontend/web') . $img;
                if( file_exists($file) && is_file($file) ) unlink($file);
            }
        } else {
            if( $this->img !== '' ){//删除
                $file = yii::getAlias('@frontend/web') . $img;
                if( file_exists($file) && is_file($file) ) unlink($file);
                $this->img = '';
            }else {
                $this->img = $img;
            }
        }

        if( $img != '' ){//修改
            foreach ($banners as &$banner){
                if( $banner['img'] == $img ){
                    $banner = [
                        'img' => $this->img,
                        'target' => $this->target,
                        'desc' => $this->desc,
                        'link' => $this->link,
                        'sort' => $this->sort,
                    ];
                }
            }
        }else {//新增
            $banners[] = [
                'img' => $this->img,
                'target' => $this->target,
                'desc' => $this->desc,
                'link' => $this->link,
                'sort' => $this->sort,
            ];
        }
        $model->value = json_encode($banners);
        return $model->save(false);
    }

    public function deleteBanner($id, $img)
    {
        $banners = $this->getBannersById($id);
        $temp = [];
        foreach ($banners as $banner){
            if($banner['img'] == $img) continue;
            $temp[] = ArrayHelper::toArray($banner);
        }
        $model = self::findOne($id);
        $model->value = json_encode($temp);
        $model->save(false);
    }

}