<?php
/**
 * Ahthor: lf
 * Email: job@feehi.com
 * Blog: http://blog.feehi.com
 * Date: 2016/4/711:37
 */
namespace backend\models;

use Feehi\Upload;
use yii;
use yii\behaviors\TimestampBehavior;

class FriendLink extends \common\models\FriendLink
{
    
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public function beforeSave($insert)
    {
        if(isset($_FILES['FriendLink']['name']['image']) && $_FILES['FriendLink']['name']['image'] != ''){
            $file = new Upload();
            if ( false == ($uri = $file->upload( yii::getAlias('@friendlylink') )) ) {
                $this->addError( 'image', yii::t('app', 'Upload {attribute} error', ['attribute' => yii::t('app', 'Image')]).': '.$uri[0] );
                return false;
            }else{
                $this->image = $uri[0];
            }
        }
        if($this->image == '') unset($this->image);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}