<?php
/**
 * Created by PhpStorm.
 * User: f
 * Date: 16/6/15
 * Time: 上午9:25
 */
namespace feehi\widgets;

use yii;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class Bar extends Widget
{
    public $buttons = [
        [
            'class' => 'btn btn-white btn-sm refresh',
            'text' => 'Refresh',
            'url' => ['refresh'],
            'iClass' => 'fa fa-refresh',
        ],
        [
            'class' => 'btn btn-white btn-sm',
            'text' => 'Create',
            'url' => ['create'],
            'iClass' => 'fa fa-plus',
        ],
        [
            'class' => 'btn btn-white btn-sm sort',
            'text' => 'Sort',
            'url' => ['sort'],
            'iClass' => 'fa  fa-sort-numeric-desc',
        ],
        [
            'class' => 'btn btn-white btn-sm multi-operate',
            'text' => 'Delete',
            'url' => ['delete'],
            'iClass' => 'fa fa-trash-o',
        ],
    ];
    public $options = [
        'class' => 'mail-tools tooltip-demo m-t-md',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $buttons = '';
        foreach ($this->buttons as $button){
            $options = [
                'class' => $button['class']
            ];
            if($button['text'] == 'Delete') $options['data-confirm'] = yii::t('app', 'Realy to delete?');
            $buttons .= Html::a("<i class='{$button['iClass']}'></i> ".yii::t('app', $button['text']), Url::to($button['url']), $options).' ';
        }
        ActiveForm::begin(['action'=>Url::to(['sort']), 'options'=>['class'=>'form-horizontal', 'name'=>'sort']]); 
        ActiveForm::end();
        return "<div class='{$this->options['class']}'>{$buttons}</div>";
    }
}